version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper:latest
    ports:
      - "2181:2181"
    container_name: zookeeper
  kafka:
    image: wurstmeister/kafka:2.11-0.11.0.3
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: MacBook-Pro.local  #your hostname 
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "logstash_logs:1:1"
    links:
      - zookeeper
    depends_on:
      - zookeeper
    container_name: kafka
  logstash:
    image: logstash:7.9.2
    ports:
      - "10000:10000"
    links:
      - kafka
    volumes:
      - ./logstash_settings/:/usr/share/logstash/config/
      - ./logstash_pipeline/:/usr/share/logstash/pipeline/
    container_name: logstash